//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace TeliaCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Contact = new HashSet<Contact>();
        }
    
        public int Id { get; set; }
        
        public string Title { get; set; }
        
        public string Description { get; set; }
   
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public System.DateTime? StartDate { get; set; }
   
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public System.DateTime? EndDate { get; set; }
   
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{t}")]
        public System.DateTime? StartTime { get; set; }
        
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{t}")]
        public System.DateTime? EndTime { get; set; }

        public string Host { get; set; }
        
        public int RoomId { get; set; }
        
        public bool MealOrderWanted { get; set; }
        
        public List<int> ContactIds { get; set; }

        public virtual ICollection<Contact> Contact { get; set; }
        public virtual MealOrder MealOrder { get; set; }
        public virtual Room Room { get; set; }
    }
}
