//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeliaCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Booking = new HashSet<Booking>();
            this.MealOrder = new HashSet<MealOrder>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Initials { get; set; }
        public int PhoneNumber { get; set; }
        public Nullable<int> MobileNumber { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
        public bool IsOnline { get; set; }
        public System.DateTime LastOnline { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> RememberMe { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual ICollection<MealOrder> MealOrder { get; set; }
    }
}
