//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeliaCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealOrder
    {
        public MealOrder()
        {
            this.Refreshments = new HashSet<RefreshmentItem>();
        }
    
        public int Id { get; set; }
        public int NumberOfDiningGuests { get; set; }
        public System.DateTime DishWishServedAt { get; set; }
        public string DepartmentCharged { get; set; }
        public string DepartmentCreditNumber { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual ICollection<RefreshmentItem> Refreshments { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
