//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeliaCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefreshmentItem
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public int MealOrdersId { get; set; }
    
        public virtual MealOrder MealOrders { get; set; }
        public virtual Product Product { get; set; }
    }
}
